spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: test
#logging:
#  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG

#---
#spring:
#  config:
#    activate:
#      on-profile: default
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false
#upload:
#  rootPath: /
#server:
#  port: ${SERVER_PORT:8081}
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: jdbc:mysql://ls-15a7d8f1c59c7a27476747ae67db4e801507eab8.cjynkhhf987n.ap-northeast-2.rds.amazonaws.com:3306/test?autoReconnect=true&useSSL=false
#upload:
#  rootPath: /home/centos/demo-upload/
#server:
#  port: 80
