server:
  port: ${SERVER_PORT:8081}
spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false
    username: test
    password: test
upload:
  rootPath: /
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG